--- #YAML:1.0
name:               Crypt-SimpleGPG
version:            0.2
abstract:           easy encryption and decryption using GPG
author:
    - Corey Cossentino ()
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:    0.22
    IPC::Run:      0.84
    Test::Simple:  0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
